name: foodai-server
channels:
  - defaults
dependencies:
  - asn1crypto
  - ca-certificates
  - cctools
  - certifi
  - cffi
  - chardet
  - clang
  - clang_osx-64
  - clangxx
  - clangxx_osx-64
  - click
  - compiler-rt
  - cryptography
  - flask
  - freetype
  - gevent
  - greenlet
  - h5py
  - hdf5
  - idna
  - intel-openmp
  - itsdangerous
  - jinja2
  - jpeg
  - keras
  - ld64
  - libcxx
  - libcxxabi
  - libedit
  - libffi
  - libgfortran
  - libpng
  - libprotobuf
  - libtiff
  - llvm
  - llvm-lto-tapi
  - markupsafe
  - mkl
  - mkl-service
  - ncurses
  - numpy
  - olefile
  - openssl
  - pillow
  - pip
  - protobuf
  - pycparser
  - pyopenssl
  - pysocks
  - python
  - pyyaml
  - readline
  - requests
  - scipy
  - setuptools
  - six
  - sqlite
  - tensorflow
  - theano
  - tk
  - urllib3
  - werkzeug
  - wheel
  - xz
  - yaml
  - zlib
